function p = janatalabpublic_pathdef
%PATHDEF Search path defaults.
%   PATHDEF returns a string that can be used as input to MATLABPATH
%   in order to set the path.

  
%   Copyright 1984-2000 The MathWorks, Inc.
%   $Revision: 1.4 $ $Date: 2000/06/01 16:19:21 $

% PATH DEFINED HERE -- Don't change this line.

if strmatch(computer,'PCWIN')
    path_sep = ';';
else
    path_sep = ':';
end

this_path = which('janatapublic_pathdef.m');
public_path = this_path(1:findstr(this_path,'janatapublic_pathdef.m')-1);

p = [...
      fullfile(public_path,['utils' path_sep]),...
      fullfile(public_path,'utils',['parser' path_sep]),...
      fullfile(public_path,'utils',['physio' path_sep]),...
      fullfile(public_path,'utils',['signal' path_sep]),...
      fullfile(public_path,'utils',['plot' path_sep]),...
      fullfile(public_path,['database' path_sep]), ...
      fullfile(public_path,'database',['fmri' path_sep]), ...
      fullfile(public_path,'database','fmri',['regressors' path_sep]), ...
      fullfile(public_path,'database',['physio' path_sep]),...
      fullfile(public_path,'fmri',['fsl' path_sep]),...
      fullfile(public_path,'fmri',['spm5_struct_templates' path_sep]),...
      fullfile(public_path,'fmri',['utils' path_sep]),...
      fullfile(public_path,'fmri','utils',['physio' path_sep]),...
      fullfile(public_path,'fmri','utils',['GE2SPM' path_sep]),...
      fullfile(public_path,'fmri','utils',['vanhorn' path_sep]),...
      fullfile(public_path,['colormaps' path_sep]),...
      fullfile(public_path,'eeg',['eeglab_petrmods' path_sep]),...
      fullfile(public_path,'eeg',['fixes' path_sep]),...
      fullfile(public_path,'eeg',['utils' path_sep]),...
      ];
%       fullfile(public_path,['miditoolbox' path_sep]),...
%       fullfile(public_path,['fmri' path_sep]), ...
%       fullfile(public_path,'fmri',['spm5_fixes' path_sep]), ...
%       fullfile(public_path,'fmri',['spm5' path_sep]),...
%       fullfile(public_path,'fmri',['spm5_struct_templates' path_sep]),...
%       fullfile(public_path,'fmri','spm99',['brett' path_sep]),...
%       fullfile(public_path,'fmri',['spm99' path_sep]),...
%       fullfile(public_path,'fmri','spm99',['spm_extensions' path_sep]),...
%       fullfile(public_path,'fmri',['cbiNifti' path_sep]),...
%       fullfile(public_path,'fmri',['mri_toolbox' path_sep]),...
%       fullfile(public_path,'models',['IPEMToolbox'  path_sep]),...
%       fullfile(public_path,'models','IPEMToolbox',['Common' path_sep]),...
%       genpath(fullfile(public_path,'models','IPEMToolbox','Demos')),...
%       fullfile(public_path,'models',['somtoolbox' path_sep]), ...
%       genpath(fullfile(public_path,'psychophysics')),...
%       genpath(fullfile(public_path,'models','aim2003')),...
%       genpath(fullfile(public_path,'functional_data_analysis')),...
%       genpath(fullfile(public_path,'stats')),...
%       fullfile(public_path,'eeg',['fixes' path_sep]), ...
%       fullfile(public_path,'eeg',['utils' path_sep]), ...
%       fullfile(public_path,'eeg',['eeglab_petrmods' path_sep]), ...
%       fullfile(public_path,'eeg',['eeglab' path_sep]),...
%       fullfile(public_path,'eeg','eeglab',['functions' path_sep]),...
%       fullfile(public_path,'eeg',['eeg_toolbox' path_sep]),...
%       genpath(fullfile(public_path,'eeg','egis')),...
%       fullfile(public_path,'eeg',['erpss' path_sep]),...
%       fullfile(public_path,'models',['head_models' path_sep]),...
%       fullfile(public_path,'models','head_models',['mesh_dipole_tool' path_sep]),...
%       fullfile(public_path,'models','head_models',['eeg_toolbox_modifications' path_sep]),...
%       fullfile(public_path,'models','head_models',['data_file_io' path_sep]),...
%       fullfile(public_path,'models','head_models',['format_conversions' path_sep]),...
%       fullfile(public_path,'models','head_models',['utils' path_sep]),...
%       fullfile(public_path,'models','head_models',['simulations' path_sep]),...

