function data_st = read_itunes_playlist(fname)
% Reads a playlist text file generated by iTunes and returns an
% Ensemble-style data struct

% 25Dec2013 Petr Janata

if nargin < 1
  error('Filename containing playlist not specified');
elseif ~exist(fname,'file')
  error('File not found: %s', fname);
end

% Initialize the output data struct
data_st = ensemble_init_data_struct;
data_st.type = 'playlist';

data_st.meta.filename = fname;

% Open the file
fid = fopen(fname,'rt');

% Read the headerline
hdrline = fgetl(fid);
vars = regexp(hdrline,'\t','split'); % Parse the variable names
vars = lower(regexprep(vars,'\s','_')); % Regularlize the varibale names
nvars = length(vars);

data_st.vars = vars; % copy variable names to output structure

% Initialize the cell array
data_st.data = cell(1,nvars);

% Read in the rest of the playlist 
[data_st.data(:)] = textscan(fid,[repmat('%s',1,nvars)],'delimiter','\t');

% Close the file
fclose(fid);

return